"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from project.settings.core import base, assets, security, i18n


class Local(
    base.Base,
    assets.Assets,
    security.Security,
    i18n.I18N
    ):
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

class Production(
    base.Base,
    assets.Assets,
    security.Security,
    i18n.I18N
    ):
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False

class Test(
    base.Base,
    assets.Assets,
    security.Security,
    i18n.I18N
    ):
    pass