name: Deploy

on:
  push:
    branches:
      -  develop
      -  master

env:
  CI_SETTINGS__TUSK_VERSION: v0.5.1
  CI_SETTINGS__DOCKER_REPO: docker.pkg.github.com/airtonix/django

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Local bin path
        run: echo "::add-path::~/bin"

      - name: Install tusk
        run: >-
          curl -sL https://git.io/tusk | sh -s --
          -b ~/bin $CI_SETTINGS__TUSK_VERSION

      - uses: actions/checkout@v1

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build ci image
        run: >-
          tusk docker:build
          --source=backend
          --repo=$CI_SETTINGS__DOCKER_REPO/backend

      - name: Publish image
        run: >-
          tusk docker:publish
          --image=$CI_SETTINGS__DOCKER_REPO/backend
          --tag=$CI_SETTINGS__DOCKER_REPO/backend:builder;
          tusk docker:publish
          --image=$CI_SETTINGS__DOCKER_REPO/backend
          --tag=$CI_SETTINGS__DOCKER_REPO/backend:$GITHUB_SHA;
          tusk docker:publish
          --image=$CI_SETTINGS__DOCKER_REPO/backend
          --tag=$CI_SETTINGS__DOCKER_REPO/backend:latest;

      - name: Rewrite Templates
        run: >-
          tusk docker:templates
          --version=$GITHUB_SHA

      - uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
        with:
          add: docker-compose*
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged